config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "crawls#home"

  resources :users, only: [:index] do
    member do
      post :follow
      post :unfollow
    end
  end

  resources :crawls, only: [:home, :index, :new, :create, :show ] do
    resources :reviews, only: [:new, :create]
    resources :shared_withs, only: [:create]
    resources :crawlbars, only: [:create]
  end

  resources :users, only: [:destroy]
  get 'dashboard', to: 'users#dashboard'
  # delete "dashboard", to: "users#destroy"
  # get 'generate', to: 'crawls#generate'
  get 'friends', to: 'users#friends'

  resources :bar, only: [] do
    resources :favourites, only: [:new, :create]
  end

  resources :reviews, only: [:destroy]
end

app/models/crawl.rb
class Crawl < ApplicationRecord
  belongs_to :user
  has_many :crawlbars, dependent: :destroy
  has_many :bars, through: :crawlbars
  has_many :reviews
  has_one :shared_withs

  validates :crawl_name, presence: true
  validates :completed, inclusion: { in: [true, false] }
  validates :public, inclusion: { in: [true, false] }


end

app/controllers/crawls_controller.rb
class CrawlsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]


  def home
    @crawl = Crawl.all.sample

    @markers = @crawl.bars.geocoded.map do |bar|
      {
        lat: bar.latitude,
        lng: bar.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: { bar: }),
        marker_html: render_to_string(partial: "marker")
      }
    end

    # puts @crawl.bars
    # puts @markers
  end
  def index

    @creators = Crawl.all.select { |crawl| crawl.creator == true }
    @public = Crawl.all.select { |crawl| crawl.public == true }
    # @public = Crawl.find_by(public: true)
    @current_friends = User.all.select do |user|
      if current_user.is_following?(user.id) && user.is_following?(current_user.id)
        user
      end
    end
    @my_friends_bars = []
    @current_friends.each do |friend|
      bars = Crawl.select { |crawl| crawl.user_id == friend.id }
      bars.each { |bar| @my_friends_bars << bar }
    end


    # @bars = Bar.all
    @creators_info = []
    @public_info = []
    @friends_info = []

    @creators.each do |crawl|
      all_crawl_info = {
        crawl:,
        markers: crawl.bars.geocoded.map do |bar|
          {
            lat: bar.latitude,
            lng: bar.longitude,
            info_window_html: render_to_string(partial: "info_window", locals: { bar: }),
            marker_html: render_to_string(partial: "marker")
          }
        end
      }

      @creators_info << all_crawl_info
    end

    clone = @public[6]
    @public.delete_at(6)
    @public = (@public.shuffle << clone)

    @public.each do |crawl|
      all_crawl_info = {
        crawl:,
        markers: crawl.bars.geocoded.map do |bar|
          {
            lat: bar.latitude,
            lng: bar.longitude,
            info_window_html: render_to_string(partial: "info_window", locals: { bar: }),
            marker_html: render_to_string(partial: "marker")
          }
        end
      }
      @public_info << all_crawl_info
    end
    @my_friends_bars.each do |crawl|
      all_crawl_info = {
        crawl:,
        markers: crawl.bars.geocoded.map do |bar|
          {
            lat: bar.latitude,
            lng: bar.longitude,
            info_window_html: render_to_string(partial: "info_window", locals: { bar: }),
            marker_html: render_to_string(partial: "marker")
          }
        end
      }
      @friends_info << all_crawl_info
    end
    @friends_info
  end

  def new
    @filters_local = filters
    # params[:bar] = []
    if params[:bars].present?
      puts "ALL FILTERED"
      puts params[:bars]
      puts @filtered_bars
      puts "-----------"

      @all_bars = @filters_local[0].map do |bar|
        Bar.new(
          name: bar.name,
          types: bar.types,
          # restaurant: bar.types,
          location: bar.location,
          longitude: bar.longitude,
          latitude: bar.latitude,
          price_range: bar.price_range,
          rating: bar.rating,
          place_id: bar.place_id,
          description: bar.description,
          image_url: bar.image_url
        )
      end
      # raise

      puts "This is @filtered_bars_ids"
      puts @filtered_bars_ids = params[:bars].split(",")
      @filtered_bars_ids = params[:bars].split(",")

      puts "all bars"
      @all_bars.each { |bar| puts bar.place_id }
      puts "---------------------"

      @filtered_bars = []
      @filtered_bars_ids.each do |bar_id|
        puts "--------------------"
        puts "bar_id"
        puts bar_id
        @all_bars.each do |bar|
          if bar.place_id == bar_id
            @filtered_bars << bar
            puts "bar"
            puts bar.place_id
            puts bar
          end
        end
      end
      puts "this is the filtered bars array"
      puts @filtered_bars


      puts "This is @filtered_bars.map(&:name)"
      puts (@filtered_bars.map{ |bar| bar.name })


      @new_bars = []

      @filtered_bars.each_with_index do |bar, i|
        if params["bar_#{i}"] == "saved"
          @new_bars << bar
        else
          new_regen_bar = bar
          until !@filtered_bars.include?(new_regen_bar)
            new_regen_bar = @all_bars.sample
          end
          until !@new_bars.include?(new_regen_bar)
            new_regen_bar = @all_bars.sample
          end
          @new_bars << new_regen_bar
        end
      end

      @new_bars_ids = @new_bars.map { |bar| bar.place_id }

      # puts @new_bars.map(&:name)
      @markers = @new_bars.map do |bar|
        {
          lat: bar.latitude,
          lng: bar.longitude,
          info_window_html: render_to_string(inline: "<div><%= bar.name %></div>", locals: { bar: bar }),
          # marker_html: render_to_string(partial: "marker")
        }
      end

      # raise
    else

      @all_bars = @filters_local[0]
      @number_of_bars = @filters_local[1]
      @filtered_bars = @all_bars.sample(@number_of_bars)


      @all_bars_info = []

      @all_bars.each do |bar|
        @all_bars_info << bar.attributes
      end

      @filtered_bars_ids = @filtered_bars.map(&:place_id)
      @markers = @filtered_bars.map do |bar|
        {
          lat: bar.latitude,
          lng: bar.longitude,
          info_window_html: render_to_string(inline: "<div><%= bar.name %></div>", locals: { bar: bar }),
          # marker_html: render_to_string(partial: "marker")
        }
      end
    end

    # * Connected with the generate() in reload.js stimulus
    @crawl = Crawl.new
    respond_to do |format|
      format.html # Follow regular flow of Rails
      format.text do
        puts "These bars from generate() fetch"
        # puts @new_bars
        puts @new_bars[0].name
        puts @new_bars[1].name
        puts @new_bars[2].name

        @filters_local = filters
        @all_bars = @filters_local[0]

        @all_bars_info = []

        @all_bars.each do |bar|
          @all_bars_info << bar.attributes
        end

        new_crawl = {
          crawl: @crawl,
          # markers: @new_bars.geocoded.map do |bar|
          markers: @new_bars.map do |bar|
                     {
                       lat: bar.latitude,
                       lng: bar.longitude,
                       info_window_html: render_to_string(inline: "<div><%= bar.name %></div>", locals: { bar: bar }),
                      #  marker_html: render_to_string(partial: "marker")
                     }
                   end
        }

        puts new_crawl
        puts new_crawl[:markers]

        # render partial: "crawls/barcards_regeneration", formats: %i[text html], locals: { filtered_bars: @new_bars }
        # render partial: "shared/map", locals: { markers: new_crawl[:markers] }
        puts

        render partial: "crawls/gen_crawl", formats: %i[text html], locals: { filtered_bars: @new_bars, markers: new_crawl[:markers], bars_full_info: @all_bars_info }
        # render partial: "crawls/gen_crawl", formats: %i[text html], locals: { markers: new_crawl[:markers] }

        # raise
      end
    end

    # raise
  end

  def show
    @crawl = Crawl.find(params[:id])
    @markers = @crawl.bars.map do |bar|
      {
        lat: bar.latitude,
        lng: bar.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: { bar: }),
        marker_html: render_to_string(partial: "marker")
      }
    end
  end

  def create

    @crawl = Crawl.new(crawl_params)
    @crawl.user = current_user
    @crawl.save!

    if params[:crawl][:existing_crawl] == "true"

      crawlbar_ids = eval(params[:crawl][:bars])
      bars = crawlbar_ids.map { |id| Crawlbar.find(id).bar }

      bars.each do |bar|
        temp = Crawlbar.new()
        temp.bar = bar
        temp.crawl = @crawl
        temp.save!
      end


    else

  bar_info = eval(params[:crawl][:bars_full_info].gsub("} {", "}, {").insert(0, "[").insert(-1, "]"))
  @all_bars = bar_info.map do |bar|
    Bar.create!(
      name: bar["name"],
      types: bar["types"],
      # restaurant: bar["types"],
      location: bar["location"],
      longitude: bar["longitude"],
      latitude: bar["latitude"],
      price_range: bar["price_range"],
      rating: bar["rating"],
      place_id: bar["place_id"],
      description: bar["description"],
      image_url: bar["image_url"]
    )
  end
  puts "all bars in create"
  puts @all_bars

    # @all_bars = @all_bars_hash.map do |bar|
    # Bar.new(
    #   name: bar["name"],
    #   types: bar["types"],
    #   # restaurant: bar["types"],
    #   location: bar["location"],
    #   longitude: bar["longitude"],
    #   latitude: bar["latitude"],
    #   price_range: bar["price_range"],
    #   rating: bar["rating"],
    #   place_id: bar["place_id"],
    #   description: bar["description"],
    #   image_url: bar["image_url"]
    # )
    # end

    @selected_bar_place_ids = params[:crawl][:bars_ids].split()

    puts "selected bar place ids in create"
    puts @selected_bar_place_ids

    @selected_bars = []
    @selected_bar_place_ids.each do |bar_place_id|
      @selected_bars << @all_bars.find { |bar| bar.place_id == bar_place_id }
    end

    @selected_bars.each do |bar|
      temp = Crawlbar.new()
      temp.crawl = @crawl
      temp.bar = bar
      temp.save!
    end
  end

      # @bars = eval(params[:crawl][:bars]).map do |id|
      #   Crawlbar.find(id).bar
      # end
  # end

#     @bars = params[:crawl][:bars].split
#     @bars.each do |id|
#       bar = Bar.find(id.to_i)
#       crawl_bar = Crawlbar.new
    # @bars.each do |bar|
    #   crawl_bar = Crawlbar.new()
    #   crawl_bar.bar = bar
    #   crawl_bar.crawl = @crawl
    #   crawl_bar.save
    # end

    redirect_to dashboard_path
  end


  # def map
  #   @markers = @new_bars.map do |bar|
  #     {
  #       lat: bar.latitude,
  #       lng: bar.longitude,
  #       # info_window_html: render_to_string(partial: "info_window", locals: { bar: bar }),

app/views/crawls/_barcards.html.erb
<%#= link_to request.params.merge("bar_#{i}" => bar.attributes) do %>
  <div class="card px-0 bg-white rounded-30 m-2" style="min-width: 30%">
    <%= image_tag bar.image_url, style:"height: 100px; object-fit: cover; border-radius:30px 30px 0px 0px", alt:"Bar card image", class:"card-img-top card-image" %>
    <div class="card-body">
      <h5 class="card-title"><strong><%= bar.name %></strong></h5>
      <% if bar.description.length > 90 %>
      <p class="card-text"><%= bar.description.truncate(90, omission: '') %>...</p>
      <% else %>
      <p class="card-text"><%= bar.description %></p>
      <% end %>
      <h6><strong><% bar.price_range.to_i.times do %>£<% end %></strong></h6>
      <h6>
      <% bar.rating.to_i.times do  %>
        <i class="fa-solid fa-star fa-lg" style="color:#ffdd00"> <span class="icon-text"></span></i>
      <% end %>
      <%= bar.rating %>
      </h6>
    </div>
  </div>
<%# end %>

app/views/crawls/_barcards_regeneration.html.erb
<div class="mt-4 container barcards-container" data-reload-target="barsList">
  <% filtered_bars.each_with_index do |bar, i| %>
    <div class="card px-0 bg-white rounded-30 m-2" style="min-width: 30%; cursor: pointer;" data-action="click->reload#keepBar" data-bar="<%= i %>">
      <%= image_tag bar.image_url, style:"height: 100px; object-fit: cover; border-radius:30px 30px 0px 0px", alt:"Bar card image", class:"card-img-top card-image" %>
      <div class="card-body">
        <h5 class="card-title"><strong><%= bar.name %></strong></h5>
        <% if bar.description.length > 90 %>
        <p class="card-text"><%= bar.description.truncate(90, omission: '') %>...</p>
        <% else %>
        <p class="card-text"><%= bar.description %></p>
        <% end %>
        <h6><strong><% bar.price_range.to_i.times do %>£<% end %></strong></h6>
        <h6>
        <% bar.rating.to_i.times do  %>
          <i class="fa-solid fa-star fa-lg" style="color:#ffdd00"> <span class="icon-text"></span></i>
        <% end %>
        <%= bar.rating %>
        </h6>
      </div>
    </div>
  <% end %>
</div>

app/views/crawls/_gen_crawl.html.erb
<div class="">
  <div class="">
    <div class="d-flex justify-content-center new-crawl-bars-map">
      <div class="card mx-5 mt-2" style="overflow:hidden; border-radius: 35px; width:1250px">
        <%= render "shared/map", markers: markers %>
      </div>
    </div>

    <div data-controller="reload" data-reload-bars-value=<%= @new_bars_ids.to_json %>>
      <%# @filtered_bars.each_with_index do |bar, i| %>

        <%= render "barcards_regeneration", filtered_bars: @new_bars %>

        <div class="d-flex justify-content-center my-2">
          <%# <button type="button" class="btn btn-primary mx-2">Confirm</button> %>
          <%= form_with model: @crawl do |f| %>
            <div class="d-none">
              <%= f.hidden_field(:bars, value: @new_bars) %>
              <%= f.hidden_field(:bars_ids, value: @new_bars.map { |bar| bar.place_id}) %>
              <%= f.hidden_field(:bars_full_info, value: @all_bars_info) %>
              <%#= f.hidden_field(:all_bars_base_64, value: @all_bars_base64) %>
              <%= f.label :crawl_name %>
              <%= f.text_field :crawl_name, value: "#{current_user.username.capitalize}'s BarHop" %>
              <%= f.label :completed %>
              <%= f.text_field :completed, value: false %>
              <%= f.label :public %>
              <%= f.text_field :public, value: false %>
              <%= f.label :date %>
              <%= f.date_field :date, value: Date.parse("Sat, 24 Jun 2023") %>
            </div>
            <%= f.submit "Save your BarHop", class: "btn btn-primary mx-2" %>
          <% end %>
          <button type="button" data-action="click->reload#generate" class="active-tab">Regenerate</button>
        </div>
        <%# end %>
      </div>
    </div>
  </div>
</div>

app/views/crawls/_info_window.html.erb
<%= bar.name %>

app/views/crawls/_marker.html.erb
<%# <%=  image_tag "pin-map.png", height: 30, width: 30, alt: "logo" %> %>

app/views/crawls/create.html.erb
<h1>Crawls#create</h1>
<p>Find me in app/views/crawls/create.html.erb</p>

app/views/crawls/home.html.erb
<div class="background-container">
  <%= image_tag "sky_garden.jpg", alt:"", class:"background-image" %>
  <div class="container home-fullpage">
    <div style="position: absolute;">
      <%# <h1 class="my-2 text-red" style="z-index: 2">BarHop</h1> %>
      <h2 class="mb-4" style="z-index: 2; color: white; font-weight: 700">Streamline your <span class="text-red ">night out</span>, discover new bars!</h2>
      <form class="search-box" action="/crawls" accept-charset="UTF-8" method="get">
        <input type="text" name="query" id="query" placeholder="Where to?">
        <button type="submit" name="commit" value="Search" class="search-icon" data-disable-with="Search" style="border:0"><i class="fas fa-search"></i></button>
      </form>
    </div>
  </div>
</div>

<div class="container">
  <h3 class="homepage-featured m-4">Featured BarHop</h3>
  <div class="mt-4 barcards-container">
    <% @crawl.bars.each do |bar| %>
      <%= render "barcards", bar: bar %>
    <% end %>
  </div>
</div>

<div class="container mb-3 px-0 mt-0">
  <div class="card mt-2 shadow-sm rounded-30">
    <div class="rounded-30 m-2" style="overflow:hidden">
      <%= render "shared/uninteractive_main_map" %>
    </div>
  </div>
</div>

app/views/crawls/index.html.erb
<div data-controller="generate-button" class="">
  <div class="" id="page" data-generate-button-target="page">
    <div class="d-flex p-4" data-controller="tabs">
      <div class="sticky">
        <%= render "shared/filters" %>
      </div>
      <div class="d-flex flex-column" style="height: 90vh">
        <div class="d-flex justify-content-center pe-4 mb-2">
          <h5 data-tabs-target="friendsButton"  data-action="click->tabs#hideShowFriends"  class="mx-2 mt-2 hoverCursor activeTabIndex friendButton">Friends</h5>
          <h5 data-tabs-target="publicButton"  data-action="click->tabs#hideShowPublic"  class="mx-2 mt-2 hoverCursor publicButton">Public</h5>
        </div>
        <div data-tabs-target="publicCards" class="index-crawls d-none">
          <% @public_info.each do |info| %>
            <%= render "shared/routecards", info: info%>
          <% end %>
        </div>
        <% if @friends_info.present? %>
          <div data-tabs-target="friendsCards" class="index-crawls">
            <% @friends_info.shuffle.each do |info| %>
              <%= render "shared/routecards", info: info%>
            <% end %>
          </div>
        <% else %>
          <div data-tabs-target="friendsCards" class="card mx-5 mt-2" style="width: 56rem;">
            <div class="card-body d-flex justify-content-around">
              <h5 class="card-title mt-2">Your friends dont have any bar crawls</h5>
              <%= link_to users_path do %>
                <i class="fa-solid fa-user-group mt-3">+</i>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="container loading-page hidden" style="height: 90vh" data-generate-button-target="spinner" id="spinner">
    <div class="spinner-border text-primary" role="status">
      <span class="visually-hidden"></span>
    </div>
    <h3 class="text-red">Generating your custom BarHop</h3>
  </div>
</div>

app/views/crawls/new.html.erb
<div class="" id="page">
  <div class="" data-controller="new-loading">
    <div class="" data-new-loading-target="page">
    <h3 class="text-center m-2"><%= current_user.username.capitalize %>'s BarHop</h3>
      <div class="d-flex justify-content-center new-crawl-bars-map">
        <div class="card mx-5 mt-2" style="overflow:hidden; border-radius: 35px; width:1250px">
          <%= render "shared/map" %>
        </div>
      </div>

      <div id="select" data-controller="reload" data-all-bars="<%= @all_bars_base64 %>" data-reload-bars-value=<%= @filtered_bars_ids.to_json %>>
          <%# <% @filtered_bars.each_with_index do |bar, i| %>
            <%= render "barcards_regeneration", filtered_bars: @filtered_bars %>

        <div class="d-flex justify-content-center my-2">
        <%# <button type="button" class="btn btn-primary mx-2">Confirm</button> %>

          <%= form_with model: @crawl do |f| %>
            <div class="d-none">
              <%= f.hidden_field(:bars, value: @filtered_bars) %>
              <%= f.hidden_field(:bars_ids, value: @filtered_bars.map { |bar| bar.place_id}) %>
              <%= f.hidden_field(:bars_full_info, value: @all_bars_info) %>
              <#%= f.hidden_field(:all_bars_base_64, value: @all_bars_base64) %>
              <%= f.label :crawl_name %>
              <%= f.text_field :crawl_name, value:"#{current_user.username.capitalize}'s BarHop"%>
              <%= f.label :completed %>
              <%= f.text_field :completed, value: false %>
              <%= f.label :public %>
              <%= f.text_field :public, value: false %>
              <%= f.label :date %>
              <%= f.date_field :date, value: Date.parse('Sat, 24 Jun 2023') %>
            </div>
            <%= f.submit 'Save your BarHop', class: "btn btn-primary mx-2" %>
          <% end %>

          <button type="button" data-action="click->reload#generate" data-action="click->new-loading#switch" class="active-tab">Regenerate</button>
        </div>
      </div>
    </div>
  </div>
  </div>
  <div class="container loading-page hidden" style="height: 90vh" data-new-loading-target="spinner" id ="spinner">
    <div class="spinner-border text-primary" role="status">
      <span class="visually-hidden"></span>
    </div>
    <h3 class="text-red">Optimizing your BarHop</h3>
  </div>

app/views/crawls/show.html.erb
<h3 class="text-center m-2"><%= @crawl.crawl_name%></h3>
<div class="d-flex justify-content-center">
  <div class="card mx-5 mt-2" style="overflow:hidden; border-radius: 35px; width:1250px">
    <%= render "shared/map" %>
  </div>
</div>

<div class="mt-4 container barcards-container">
  <% @crawl.bars.each do |bar| %>
    <%= render "crawls/barcards", bar: bar %>
  <% end %>
</div>

<div class="d-flex justify-content-center my-2" data-controller="reload">
  <%# <button type="button" class="btn btn-primary mx-2">Confirm</button> %>
  <%= form_with model: Crawl.new do |f| %>
    <%= f.hidden_field(:existing_crawl, value: true) %>
      <%# <form action="/crawls" accept-charset="UTF-8" method="post"><input type="hidden" name="_method" value="patch" autocomplete="off"><input type="hidden" name="authenticity_token" value="fnUpUlGoAWrO2okRT6MV04lSTxgy9__3M5jugDDE9Sm4ppauZ6Nl6bktKlb1q-yzgERXcBoix3I96irFbIyjjA" autocomplete="off"> %>
    <div class="d-none">
      <input value= "<%= @crawl.crawlbar_ids %>" autocomplete="off" type="hidden" name="crawl[bars]" id="crawl_bars">
      <label for="crawl_crawl_name">Crawl name</label>
      <input value="<%= @crawl.crawl_name %>" type="text" name="crawl[crawl_name]" id="crawl_crawl_name">
      <label for="crawl_completed">Completed</label>
      <input value="false" type="text" name="crawl[completed]" id="crawl_completed">
      <label for="crawl_public">Public</label>
      <input value="false" type="text" name="crawl[public]" id="crawl_public">
      <label for="crawl_date">Date</label>
      <input value="2023-06-24" type="date" name="crawl[date]" id="crawl_date">
    </div>
    <input type="submit" name="commit" value="Save this BarHop" class="btn btn-primary mx-2" data-disable-with="Save this BarHop">
  <%# </form> %>
  <% end %>

<%= link_to "Back to BarHops", crawls_path, class:"active-tab" %>

</div>