config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "crawls#home"

  resources :users, only: [:index] do
    member do
      post :follow
      post :unfollow
    end
  end

  resources :crawls, only: [:home, :index, :new, :create, :show ] do
    resources :reviews, only: [:new, :create]
    resources :shared_withs, only: [:create]
    resources :crawlbars, only: [:create]
  end

  resources :users, only: [:destroy]
  get 'dashboard', to: 'users#dashboard'
  # delete "dashboard", to: "users#destroy"
  # get 'generate', to: 'crawls#generate'
  get 'friends', to: 'users#friends'

  resources :bar, only: [] do
    resources :favourites, only: [:new, :create]
  end

  resources :reviews, only: [:destroy]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reviews
  has_many :crawls
  has_many :favourites
  has_many :shared_withs

  has_many :follower_relationships, foreign_key: :following_id, class_name: 'Follow'
  has_many :followers, through: :follower_relationships, source: :follower

  has_many :following_relationships, foreign_key: :follower_id, class_name: 'Follow'
  has_many :following, through: :following_relationships, source: :following

  validates :username, uniqueness: true
  validates :email, uniqueness: true

  def follow(user_id)
    following_relationships.create(following_id: user_id)
  end

  def unfollow(user_id)
    following_relationships.find_by(following_id: user_id).destroy
  end

  def is_following?(user_id)
    relationship = Follow.find_by(follower_id: id, following_id: user_id)
    return true if relationship
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
  end

  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # skip_before_action :authenticate_user!
  before_action :set_user, only: [:follow, :unfollow]

  def dashboard
    # @crawl = Crawl.find(params[:id])
    # @crawls = Crawl.all
    @crawls = current_user.crawls.reverse
    # @bars = Bar.all
    @all_info = []

    @crawls.each do |crawl|
      all_crawl_info = {
        crawl:,
        markers: crawl.bars.geocoded.map do |bar|
          {
            lat: bar.latitude,
            lng: bar.longitude,
            # info_window_html: render_to_string(partial: "crawls/info_window", locals: { bar: bar }),
            # marker_html: render_to_string(partial: "crawls/marker")
          }
        end
      }
      @all_info << all_crawl_info
    end

    @all_info

    @favourite = Favourite.new


    @favourites = current_user.favourites
    @markers = @favourites.map { |favourite| {
      lat: favourite.bar.latitude,
      lng: favourite.bar.longitude,
      info_window_html: render_to_string(partial: "info_window", locals: { favourite: favourite }),
      # marker_html: render_to_string(partial: "marker")
    }}
    @bars = []
    @favourites.each do |favourite|
      if  @bars.any? { |bar| bar.id == favourite.bar_id }
        index = @bars.index { |bar| bar.id == favourite.bar_id }
        @bars.delete_at(index)
      else
        @bars << Bar.find(favourite.bar_id)
      end
    end
    #friends
    @friends = friends
  end

  def friends
    @users = User.all.select do |user|
      if current_user.is_following?(user.id) && user.is_following?(current_user.id)
        user
      end
    end
    @users
  end

  def index
    @users = User.where.not(id: current_user.id)
  end

  def follow
    if current_user.follow(@user.id)
      respond_to do |format|
        format.html { redirect_to users_path }
        format.js
      end
    end
  end

  def unfollow
    if current_user.unfollow(@user.id)
      respond_to do |format|
        format.html { redirect_to users_path }
        format.js { render action: :follow }
      end
    end
  end

  def destroy
    @crawl = Crawl.find(params[:id])
    @crawl.destroy
    redirect_to dashboard_path, status: :see_other
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

# def dashboard
#   @crawls = current_user.crawls

#   # @markers_all = []

#   # @crawls.each do |crawl|
#   #   @markers = crawl.bars.geocoded.map do |bar|
#   #     {
#   #       lat: bar.latitude,
#   #       lng: bar.longitude
#   #       # info_window_html: render_to_string(partial: "info_window", locals: { bar: bar }),
#   #       # marker_html: render_to_string(partial: "marker")
#   #     }
#   #     @markers_all.push(@markers)
#       # raise
#     # end
#   end

#   # @crawls = Crawl.all

#   # @crawl = Crawl.all.sample

#   # @markers = @crawl.bars.geocoded.map do |bar|
#   #   {
#   #     lat: bar.latitude,
#   #     lng: bar.longitude,
#   #     # info_window_html: render_to_string(partial: "info_window", locals: { bar: bar }),
#   #     # marker_html: render_to_string(partial: "marker")
#   #   }
#   # end
# # end
# end

app/views/users/_info_window.html.erb
<%= favourite.bar.name %>

app/views/users/_user.html.erb
<div class="row mx-2">
  <div class="col-12 col-sm-6 col-md-4 col-lg-3 p-0">
    <div class="friend-card" data-user="<%= user.id %>">
      <%= user.username.capitalize %>
      <br>
      <%= user.email %>
      <hr>
      <% if current_user.is_following?(user.id) && user.is_following?(current_user.id) %>
        <p>We are friends</p>
      <% else %>
        <p>We are not friends</p>
        <% if user.is_following?(current_user.id) %>
        <hr>
          <form action="/users/<%= user.id %>/follow" method="POST">
            <button type="submit" class="btn btn-primary btn-sm small-button">Accept</button>
          </form>
        <% else %>
          <% if current_user.is_following?(user.id) %>
            <form action="/users/<%= user.id %>/unfollow" method="POST">
              <button type="submit" class="btn btn-danger btn-sm small-button">Unsend</button>
            </form>
          <% else %>
            <form action="/users/<%= user.id %>/follow" method="POST">
              <button type="submit" class="btn btn-success btn-sm small-button">Send</button>
            </form>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/dashboard.html.erb
<div class="container" data-controller="favourites">
  <div data-controller="fav-barmap">
  <div class="row align-items-center py-4 border-bottom border-black">
    <div class="col">
      <h1 class="d-flex justify-content-start ">Welcome <%= current_user.username.capitalize%>👋</h1>
    </div>
    <div class="col text-end mb-1 fs-5">
      <%# <a href="#" class="p-3">Badges</a> %>
      <button data-action="click->favourites#hideShowFavourites" data-favourites-target="favouriteBarsButton" class="btn btn-outline-primary favourite-btn">Favourite Bars 🍾 </button>
      <button data-action="click->favourites#hideShowSavedBarhops" data-favourites-target="savedBarsButton" class="btn btn-outline-primary active-button">Saved BarHops ✨</button>
      <button data-action="click->favourites#hideShowFriendsButton" data-favourites-target="showFriendsButton" class="btn btn-outline-primary">Friends 👽</button>
      <%# <%= link_to "Friends 👽", friends_path, class: "btn btn-outline-primary" %>
      <%# <button class="btn btn-outline-primary">Friends 👽</button> %>
    </div>
  </div>
  <div data-favourites-target="savedBarhops" class="">
    <h2 class="m-3">Your BarHops:</h2>
    <% @crawls.each_with_index do |crawl, i| %>
      <div class="card pb-3 mb-4 rounded-30" style="overflow: hidden;" >
      <div class="dashboard-card-header">
        <h4 class="card-title dashboard-header m-0"><%= crawl.crawl_name %></h4>
        <p class="estimated-time"></p>
        <%= link_to "Delete", {:controller => "users", :action => 'destroy', :id => crawl.id}, data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: :deleteButton, remote: true %>
      </div>
        <div class="d-flex justify-content-between ps-3 pe-3">
          <div class="dashboard-container">
            <% crawl.bars.each do |bar| %>
              <div class="dashboard-card m-2">

<!--                 <img src="<%= bar.image_url %>" alt="" class="" style="; height: 100%">
                  <p class=""><strong><%= bar.name %></strong></p>
                <%= form_with model: @favourite, url: bar_favourites_path(bar) do |f| %>
                <div class="d-none">
                  <%= f.hidden_field(:bar, value: bar) %>
                </div>
                <button class="btn btn-outline-primary" type="submit" name="commit" data-disable-with="Favourite"><i class="fa-solid fa-heart"></i></button>
                <% end %> -->
<!-- ------------ -->
                  <div style ="position: relative; background-size: cover;background-position: center;height: 194px; width: 100%; background-image: url(<%= bar.image_url %>); cursor: pointer" data-bs-toggle="modal" data-bs-target="#barModal-<%= bar.id %>">
                    <%= form_with model: @favourite, url: bar_favourites_path(bar) do |f| %>
                    <div class="d-none">
                      <%= f.hidden_field(:bar, value: bar) %>
                    </div>
                    <button class="btn btn-outline-primary" style="position: absolute; top:0; right:0;border: none;" type="submit" name="commit" data-disable-with="Favourite"><i class="fa-solid fa-heart"></i></button>
                    <% end %>
                  </div>
                <p class=""><strong><%= bar.name %></strong></p>

                <!-- Modal -->
                  <div class="modal fade" id="barModal-<%= bar.id %>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered">
                      <div class="modal-content">
                        <div class="modal-header">
                          <h1 class="modal-title fs-5" id="exampleModalLabel"><%= bar.name %></h1>
                          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                        <img src="<%= bar.image_url %>" class="bar-model-image" alt="bar image">
                        <hr>
                          <%= bar.description %>
                          <hr>
                          <%= bar.location %>
                        </div>
                      </div>
                    </div>
                  </div>
<!-- ------------ -->
              </div>
                <!-- <img src="<%= bar.image_url %>" alt="" class="" style="height: 100%"> -->
                <%# <img src="https://plus.unsplash.com/premium_photo-1674374441957-39c93764b3e5?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8YmFyfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60" alt="" class=""> %>
            <% end %>
          </div>
          <div class="card ms-3 bg-white rounded-30" style="overflow: hidden;">
            <%= render "shared/dashboard_map", info:@all_info[i] %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div data-favourites-target="favouriteBars" class="container d-none">
  <%# <div data-controller="fav_barmap"> %>
  <div class="d-flex justify-content-center">
  <button data-action="click->fav-barmap#toggle" data-fav-barmap-target="buttonText" class="btn btn-outline-primary m-3 toggle-map-btn">Map of Bars 🗺️</button>
  </div>
  <div class="mb-3 px-0 mt-0 hidden" data-fav-barmap-target="map">
    <div class="card mt-2 shadow-sm rounded-30">
      <div class="rounded-30 m-2" style="overflow:hidden">
        <%= render "shared/favourites_map" %>
      </div>
    </div>
  </div>
  <%# </div> %>
    <div class="row justify-content-center" data-fav-barmap-target="barCards">
      <% @bars.uniq.each do |bar| %>
        <div class="card px-0 bg-white rounded-30 m-2 col-3">
          <%= image_tag bar.image_url, style:"height: 100px; object-fit: cover; border-radius:30px 30px 0px 0px", alt:"Bar card image", class:"card-img-top card-image" %>
          <div class="card-body ">
            <h5 class="card-title"><strong><%= bar.name %></strong></h5>
            <% if bar.description.length > 90 %>
            <p class="card-text"><%= bar.description.truncate(75, omission: '') %>...</p>
            <% else %>
            <p class="card-text"><%= bar.description %></p>
            <% end %>
            <h6><strong><% bar.price_range.to_i.times do %>£<% end %></strong></h6>
            <h6><% bar.rating.to_i.times do  %>
              <i class="fa-solid fa-star fa-lg" style="color:#ffdd00"> <span class="icon-text"></span></i>
            <% end %>
            </h6>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div data-favourites-target="showFriends" class="container d-none">
    <div class="row">
    <div class="d-flex justify-content-between">
      <h1 class="mt-2">Friends</h1>
      <%= link_to users_path do %>
              <i class="fa-solid fa-user-group mt-3">+</i>
            <% end %>
    </div>
      <% @friends.each do |friend| %>
        <div class="col-md-4">
          <div class="card">
            <div class="card-body">
              <p class="card-text">👤 : <%= friend.username.capitalize %></p>
              <hr>
              <p class="card-text">📩 : <%= friend.email %></p>
              <div style="position: relative;">
                <%# <img src="" alt="Profile Image" style="position: absolute; bottom: 0; right: 0; width: 100px; height: 100px;"> %>
              </div>
              <form action="/users/<%= friend.id %>/unfollow" method="POST">
                <button type="submit" class="btn btn-danger">Delete</button>
              </form>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  </div>
</div>

app/views/users/follow.js.erb
function renderUser(userHTML) {
  const user = document.querySelector("[data-user='<%= @user.id %>']");
  user.outerHTML = userHTML;
}

renderUser('<%= j render @user %>');

app/views/users/friends.html.erb
Your Friends

<% @users.each do |user| %>
<%= user.email %>
<% end %>

app/views/users/index.html.erb
<div class="container">
  <h1 class="mx-1 my-3" style="text-align: center;" ><i class="fa-solid fa-users" style="color: #D94124"></i></h1>

  <ul class="d-flex px-0" style="flex-wrap: wrap">
    <%= render @users %>
  </ul>
</div>