config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "crawls#home"

  resources :users, only: [:index] do
    member do
      post :follow
      post :unfollow
    end
  end

  resources :crawls, only: [:home, :index, :new, :create, :show ] do
    resources :reviews, only: [:new, :create]
    resources :shared_withs, only: [:create]
    resources :crawlbars, only: [:create]
  end

  resources :users, only: [:destroy]
  get 'dashboard', to: 'users#dashboard'
  # delete "dashboard", to: "users#destroy"
  # get 'generate', to: 'crawls#generate'
  get 'friends', to: 'users#friends'

  resources :bar, only: [] do
    resources :favourites, only: [:new, :create]
  end

  resources :reviews, only: [:destroy]
end

app/views/shared/_cards.html.erb
<div class="card m-2 px-0 bg-lp rounded-thirty" style="width:25rem">
  <% if bar.image_url.present? %>
    <img class="card-img-top card-image" style="height: 100px; object-fit: cover; border-radius:30px 30px 0px 0px" src="<%= bar.image_url %>" alt="Card image cap">
    <% else %>
    <img class="card-img-top card-image" src="https://images.unsplash.com/photo-1597290282695-edc43d0e7129?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2075&q=80" alt="Card image cap">
  <% end %>
  <div class="card-body">
    <h5 class="card-title"><strong><%= bar.name %></strong></h5>
    <% if bar.description.length > 90 %>
    <p class="card-text"><%= bar.description.truncate(90, omission: '') %>...</p>
    <% else %>
    <p class="card-text"><%= bar.description %></p>
    <% end %>
    <h6><strong><%= bar.price_range %></strong></h6>
    <h6><% bar.rating.to_i.times do  %>
      <i class="fa-solid fa-star fa-lg" style="color:#ffdd00"> <span class="icon-text"></span></i>
    <% end %>
    </h6>
  </div>
</div>

app/views/shared/_dashboard_map.html.erb
<div style="width: 30vw; height: 100%; pointer-events: none"
      data-controller="map"
      data-map-markers-value="<%= info[:markers].to_json %>"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
</div>

app/views/shared/_favourites_map.html.erb
<div style="width: 100%; height: 55vh "
      data-controller="favourites-map"
      data-favourites-map-markers-value="<%= @markers.each.to_json %>"
      data-favourites-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
</div>

app/views/shared/_filters.html.erb
  <div class="card p-4 text-center" style="width: 25rem; height: 510px" data-controller="slider-bar-range" data-controller="slider-price-range">
    <h5 class="card-title mt-2 mb-3"><strong>Create your own </strong><strong style="color: #D94124">bar crawl</strong></h5>
    <%= form_with url: new_crawl_path, method: :get, html: { class: "row search-icon", data: { controller: "slider-price-range generate-button" } } do |f| %>
      <%= f.text_field :query, value: params[:query], class: "form-control bg-white border border-black col-12", placeholder: "Location..." %>
      <h6 class="text-center mt-4 mb-0">Price</h6>
      <div class="d-flex justify-content-center my-3">
        <input type="hidden" name="price_range[]" value="" autocomplete="off">
          <input class="tag-selector" type="checkbox" value="1" name="price_range[]" id="price_range_1">
          <label class="mx-3 pound" for="price_range_1" style="font-size: 18px;"><strong>£</strong></label>
          <input class="tag-selector" type="checkbox" value="2" name="price_range[]" id="price_range_2">
          <label class="mx-3 pound" for="price_range_2" style="font-size: 18px;"><strong>££</strong></label>
          <input class="tag-selector" type="checkbox" value="3" name="price_range[]" id="price_range_3">
          <label class="mx-3 pound" for="price_range_3" style="font-size: 18px;"><strong>£££</strong></label>
          <input class="tag-selector" type="checkbox" value="4" name="price_range[]" id="price_range_4">
          <label class="mx-3 pound" for="price_range_4" style="font-size: 18px;"><strong>££££</strong></label>
      </div>
        <!-- <%= f.select :day, ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'], { :include_blank => 'Day for crawl' },  class: "form-select select-category dropdown-item my-3"  %> -->
      <h6 class="text-center mt-4 mb-0">Venue</h6>
      <div class="d-flex justify-content-around my-3" style="padding-right: 64px;">
        <input type="hidden" name="venue_category[]" value="" autocomplete="off">
        <input class="tag-selector2" type="checkbox" value="restaurant" name="venue_category[]" id="venue_category_1">
        <label for="venue_category_1"><strong style="font-size: 28px;">🍺 + 🍕</strong></label>
        <div class="vertical-line"></div>
        <input class="tag-selector2" type="checkbox" value="bar" name="venue_category[]" id="venue_category_2">
        <label for="venue_category_2"><strong style="font-size: 28px;">🍺</strong></label>
      </div>
      <h6 class="text-center mt-3 mb-2">Number of bars</h6>
      <div class="actions" data-controller="plus-minus">
        <p class="btn round-bordered incrementer minus mx-2" data-action="click->plus-minus#minusButton" id="minus">-</p>
        <span class="mb-1" id="counter" data-plus-minus-target="numberOfBars" style="font-size: 20px;"><strong>3</strong></span>
        <p class="btn round-bordered incrementer mx-2" data-action="click->plus-minus#plusButton" id="plus">+</p>
        <div class="d-none">
          <input class="form-input select-category dropdown-item my-3" data-plus-minus-target="finalBars" name="number_of_bars" id="number_of_bars" value="3"></input>
        </div>
      </div>
      <%# f.select :number_of_bars, [3, 4, 5, 6], { :include_blank => 'Prefered number of bars' }, class: "form-select select-category dropdown-item my-3" %>
      <button class="btn btn-primary mt-2" type="submit" data-generate-button-target="button" data-action="click->generate-button#generate">
        <%# <span class="spinner-border spinner-border-sm invisible" data-generate-button-target="spinner" role="status" aria-hidden="true"></span> %>
         Generate
      </button>
    <% end %>
  </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<!-- Remove the container if you want to extend the Footer to full width. -->
<div class="container mt-5 mb-3 border-top">

  <footer class=" text-center text-black">
  <!-- Grid container -->
  <div class="d-flex flex-column align-items-center">

    <div class="container p-4 pb-0">
      <!-- Section: Social media -->
      <section class="mb-3">
        <!-- Facebook -->
        <a class="btn btn-outline-black btn-floating m-1" href="#!" role="button"
          ><i class="fab fa-facebook-f footer-icon"></i
        ></a>

        <!-- Twitter -->
        <a class="btn btn-outline-black btn-floating m-1" href="#!" role="button"
          ><i class="fab fa-twitter footer-icon"></i
        ></a>

        <%# <!-- Google -->
        <a class="btn btn-outline-black btn-floating m-1" href="#!" role="button"
          ><i class="fab fa-google"></i
        ></a> %>

        <!-- Instagram -->
        <a class="btn btn-outline-black btn-floating m-1" href="#!" role="button"
          ><i class="fab fa-instagram footer-icon"></i
        ></a>
<%#
        <!-- Linkedin -->
        <a class="btn btn-outline-black btn-floating m-1" href="#!" role="button"
          ><i class="fab fa-linkedin-in"></i
        ></a>

        <!-- Github -->
        <a class="btn btn-outline-black btn-floating m-1" href="#!" role="button"
          ><i class="fab fa-github"></i
        ></a> %>
      </section>
      <!-- Section: Social media -->
    </div>
    <!-- Grid container -->

    <!-- Copyright -->
    <div class="text-center py-3" style="background-color: rgba();">
    © 2023 Copyright: BarHop
    </div>
  </div>
  <!-- Copyright -->
</footer>

</div>
<!-- End of .container -->

app/views/shared/_header.html.erb
<nav class="navbar bg-body-tertiary px-4 py-0 pb-1 border-bottom">
  <div class="container-fluid">
    <div class="d-flex align-items-center" data-controller="header">
      <%= link_to root_path do %>
        <%= image_tag "logo_no_background.png", alt:"Logo", width:"56", height:"56", class:"d-inline-block align-text-top" %>
      <% end %>
      <%= link_to "BarHop", root_path, class:"m-0 pt-3 text-red h2 header-title" %>
      <%# <h2 class="m-0 pt-3 text-red" style="font-weight: 600">BarHop</h2> %>
      <div class="search-box-minimized" data-header-target="smallDiv">
        <button data-action="click->header#maximize" class="search-icon-small" data-disable-with="" style="border:0"><i class="fas fa-search"></i></button>
      </div>
      <form class="search-box-small d-none" data-header-target="formDiv" action="/crawls" accept-charset="UTF-8" method="get">
        <input type="text" name="query" id="query" placeholder="Where to?">
        <button type="submit" name="commit" value="Search" class="search-icon-small" data-disable-with="Search" style="border:0"><i class="fas fa-search"></i></button>
      </form>
    </div>
    <div>
      <%# Changes if a login button is showed or the user avatar %>
      <% if current_user %>
        <%= link_to dashboard_path do %>
          <%= image_tag "justin.png", alt:"User Photo", class:"avatar d-inline-block align-self-center" %>
        <% end %>
      <% else %>
        <%= link_to "Login", new_user_session_path, class:"btn btn-primary m-3" %>
      <% end %>
    </div>
  </div>
</nav>

app/views/shared/_map.html.erb
<%# <div class="container mb-3 px-0 mt-0">
  <div class="card mt-2 shadow-sm">
  <div class="card m-2" style="overflow:hidden"> %>
    <div style="width: 100%; height: 40vh; "
    data-controller="map"
      data-map-markers-value="<%= @markers.to_json %>"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  <%# </div>
  </div>
</div> %>

app/views/shared/_map_inside_card.html.erb
<div style="width: 100%; height: 40vh; "
  data-controller="map"
  data-map-markers-value="<%= info[:markers].to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
</div>

app/views/shared/_routecards.html.erb
<%= link_to crawl_path(info[:crawl]), class: "route-cards-container mx-1 my-2" do %>
  <div class="card px-0 bg-white rounded-30" style ="overflow: hidden;">
      <%= render "shared/uninteractive_cards_map", info:info %>
    <div class="card-body text-center">
      <p class="crawl-name"><strong><%= info[:crawl].crawl_name %></strong></p>
    </div>
  </div>
<% end %>

app/views/shared/_uninteractive_cards_map.html.erb
<div style="width: 100%; height: 40vh; pointer-events: none"
      data-controller="map"
      data-map-markers-value="<%= info[:markers].to_json %>"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
</div>

app/views/shared/_uninteractive_main_map.html.erb
<div style="width: 100%; height: 40vh; pointer-events: none"
      data-controller="map"
      data-map-markers-value="<%= @markers.to_json %>"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
</div>

app/views/shared/_uninteractive_map.html.erb
<div style="width: 100%; height: 40vh; pointer-events: none"
      data-controller="map"
      data-map-markers-value="<%= @markers.to_json %>"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
</div>